---

- hosts: mongodb

  remote_user: ec2-user
  become: yes

  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3-pip
        - yum-utils
        - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Enable Some packages from amazon-linux-extras packages
      shell: "amazon-linux-extras enable python3.8 docker"

    - name: clean yum metadata cache
      command: yum clean metadata
      args:
        warn: false

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3.8
        - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Upgrade pip3
      shell: "python3.8 -m pip install pip --upgrade"

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
        executable: /usr/local/bin/pip3.8
      vars:
        packages:
          - boto
          - boto3
          - docker
          - docker-compose

    - name: Re-create a teamcity container
      vars:
        ansible_python_interpreter: /usr/bin/python3.8
      docker_container:
        name: teamcity-server
        image: jetbrains/teamcity-server
        state: started
        recreate: yes
        restart: yes
        ports:
          - "80:8111"

